site:
  title: OpenShellOrg Docs
  url: https://opensh.org/open-shell-org
  start_page: open-shell-org::index.adoc
  keys:
    header_logo: logo.svg
    site_home_url: https://opensh.org
    site_home_label: OpenShellOrg home
    header_doc_title: OpenShellOrg Docs

antora:
  extensions:
    - '@antora/lunr-extension'
    - require: '@antora-supplemental/alias-component-to-latest'

content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
    - url: https://github.com/openshellorg/shell-architecture.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/nu-emit.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/nu-require.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/about.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/info.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/prohelp.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/prohelp-cli.git
      branches: [main]
      start_path: docs
    - url: https://github.com/openshellorg/project-map.git
      branches: [main]
      start_path: docs

ui:
  bundle:
    url: https://github.com/antora-supplemental/valentus-theme/releases/download/v2/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""

output:
  dir: build/site
